# Production profile for EmailService
spring:
  profiles:
    active: prod
  config:
    activate:
      on-profile: prod
  application:
    name: emailservice
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  eureka:
    client:
      service-url:
        defaultZone: ${EUREKA_URL}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  zipkin:
    base-url: ${ZIPKIN_URL}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
  prometheus:
    url: ${PROMETHEUS_URL}
  grafana:
    url: ${GRAFANA_URL}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

