# Docker profile for Gateway
spring:
  profiles:
    active: docker
  config:
    activate:
      on-profile: docker
  application:
    name: gateway
  eureka:
    client:
      service-url:
        defaultZone: http://eureka-server:8761/eureka/
  kafka:
    bootstrap-servers: kafka:9092
  zipkin:
    base-url: http://zipkin:9411
  redis:
    host: redis-master
    port: 6379
    password: redispass
  prometheus:
    url: http://prometheus:9090
  grafana:
    url: http://grafana:3000

