# Docker profile for TripService
spring:
  profiles:
    active: docker
  config:
    activate:
      on-profile: docker
  application:
    name: tripservice
  datasource:
    url: jdbc:postgresql://postgres-trip:5432/trip_service_db
    username: traveluser
    password: postgres
  data:
    mongodb:
      uri: mongodb://admin:password@mongo:27017/tripdb?authSource=admin
    redis:
      timeout: 2000
      database: 0
      sentinel:
        master: mymaster
        nodes: redis-sentinel-1:26379,redis-sentinel-2:26379,redis-sentinel-3:26379
      password: redispass
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: -1ms
  cache:
    type: redis
    redis:
      time-to-live: 300000
      enable-statistics: true
  kafka:
    bootstrap-servers: kafka:9092
  zipkin:
    base-url: http://zipkin:9411
  redis:
    host: redis-master
    port: 6379
    password: redispass
  prometheus:
    url: http://prometheus:9090
  grafana:
    url: http://grafana:3000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.data.mongodb.core.MongoDatabaseFactory: DEBUG
    org.springframework.data.mongodb.core.MongoCollectionUtils: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://eureka-server:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,caches
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    cache:
      enabled: true
    distribution:
      percentiles-histogram:
        cache: true
      sla:
        cache: 50ms,100ms,200ms
  tracing:
    enabled: true
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans


app:
  user:
    service:
      base:
        url: http://gateway:8080
  admin:
    email: admin@travelmate.com
    password: Travelmate123

server:
  port:8082