global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Spring Boot microservices (Auth, Trip, Email, Gateway, Eureka)
  - job_name: 'spring-boot-services'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets:
          - 'auth-service:8083'
          - 'trip-service:8082'
          - 'email-service:8085'
          - 'gateway:8080'
          - 'eureka-server:8761'

  # User-service (Node.js)
  - job_name: 'node-service'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'user-service:5000'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'user-service'
      - source_labels: [__address__]
        target_label: service
        replacement: 'user-service'

  # Kafka
  - job_name: 'kafka'
    scrape_interval: 15s
    static_configs:
      - targets:
          - 'kafka-exporter:9308'  # Need kafka-exporter container
          - 'user-service:5000'   # Additional scrape from user-service for Kafka metrics
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'userservice_kafka_.*'
        action: keep

  # Zookeeper
  - job_name: 'zookeeper'
    scrape_interval: 15s
    static_configs:
      - targets:
          - 'zookeeper-exporter:9141'

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets:
          - 'redis-exporter:9121'
          - 'user-service:5000'   # Additional scrape from user-service for Redis metrics
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'userservice_redis_.*'
        action: keep

  # Postgres
  - job_name: 'postgres'
    static_configs:
      - targets:
          - 'postgres-exporter:9187'

  # MongoDB
  - job_name: 'mongodb'
    static_configs:
      - targets:
          - 'mongodb-exporter:9216'
