server:
  port: 8080

spring:
  application:
    name: gateway
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true
    bus:
      enabled: true
      id: ${spring.application.name}
    stream:
      kafka:
        binder:
          brokers: kafka:9092
          auto-create-topics: true
      bindings:
        springCloudBusInput:
          destination: springCloudBus
          group: ${spring.application.name}
        springCloudBusOutput:
          destination: springCloudBus
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

        - id: trip-service
          uri: lb://trip-service
          predicates:
            - Path=/api/trip/**

        - id: journal-service
          uri: lb://journal-service
          predicates:
            - Path=/api/journal/**

        - id: ai-service
          uri: lb://ai-service
          predicates:
            - Path=/api/ai/**,/api/mcp/**
    kafka:
      bootstrap-servers: kafka:9092

  profiles:
    active: docker
