apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-auth-pvc
  namespace: travelmate
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-auth
  namespace: travelmate
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-auth
  namespace: travelmate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-auth
  template:
    metadata:
      labels:
        app: postgres-auth
    spec:
      containers:
        - name: postgres-auth
          image: postgres:15-alpine
          env:
            - name: POSTGRES_DB
              value: travelmate_auth
            - name: POSTGRES_USER
              value: traveluser
            - name: POSTGRES_PASSWORD
              value: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-auth-data
              mountPath: /var/lib/postgresql/data
            - name: init-auth-database
              mountPath: /docker-entrypoint-initdb.d/init-auth-database.sql
              subPath: init-auth-database.sql
      volumes:
        - name: postgres-auth-data
          persistentVolumeClaim:
            claimName: postgres-auth-pvc
        - name: init-auth-database
          configMap:
            name: init-auth-database
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-auth-database
  namespace: travelmate
  labels:
    app: postgres-auth
data:
  init-auth-database.sql: |
    DO
    $$
        BEGIN
            IF NOT EXISTS (SELECT FROM pg_database WHERE datname = 'travelmate_auth') THEN
                CREATE DATABASE travelmate_auth;
            END IF;
        END
    $$;
