apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-user-pvc
  namespace: travelmate
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-user
  namespace: travelmate
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-user
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-user
  namespace: travelmate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-user
  template:
    metadata:
      labels:
        app: postgres-user
    spec:
      containers:
        - name: postgres-user
          image: postgres:15-alpine
          env:
            - name: POSTGRES_DB
              value: user_service_db
            - name: POSTGRES_USER
              value: traveluser
            - name: POSTGRES_PASSWORD
              value: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-user-data
              mountPath: /var/lib/postgresql/data
            - name: init-user-database
              mountPath: /docker-entrypoint-initdb.d/init-user-database.sql
              subPath: init-user-database.sql
      volumes:
        - name: postgres-user-data
          persistentVolumeClaim:
            claimName: postgres-user-pvc
        - name: init-user-database
          configMap:
            name: init-user-database
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-user-database
  namespace: travelmate
  labels:
    app: postgres-user
data:
  init-user-database.sql: |
    DO
    $$
        BEGIN
            IF NOT EXISTS (SELECT FROM pg_database WHERE datname = 'user_service_db') THEN
                CREATE DATABASE user_service_db;
            END IF;
        END
    $$;
