server:
  port: 8761

spring:
  application:
    name: eureka-server
  zipkin:
    base-url: http://zipkin:9411

eureka:
  instance:
    hostname: eureka-server
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 10000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  tracing:
    enabled: true
  zipkin:
      tracing:
        endpoint: http://zipkin:9411/api/v2/spans

logging:
  level:
    com.netflix.eureka: WARN
    com.netflix.discovery: WARN
    org.apache.kafka: WARN
    org.springframework.kafka: WARN
    org.springframework.cloud.bus: WARN
    org.springframework.cloud.stream: WARN