server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Sagar-9720/Travelmate-configs.git
          username: Sagar-9720
          password: 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
          default-label: main
          clone-on-start: true
        native:
          enabled: false
    bus:
      enabled: true
    stream:
      kafka:
        binder:
          brokers: kafka:9092
          auto-create-topics: true
      bindings:
        springCloudBusInput:
          destination: springCloudBus
          group: ${spring.application.name}
        springCloudBusOutput:
          destination: springCloudBus
  application:
    name: config-server
    profiles:
      active: git
management:
  endpoints:
    web:
      exposure:
        include: busrefresh,refresh,health,info
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: WARN
    org.springframework.data.mongodb.core.MongoDatabaseFactory: WARN
    org.springframework.data.mongodb.core.MongoCollectionUtils: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.apache.kafka: WARN
    org.springframework.kafka: WARN
    org.springframework.cloud.bus: WARN
    org.springframework.cloud.stream: WARN
