apiVersion: apps/v1
kind: Deployment
metadata:
  name: journal-service
  namespace: travelmate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: journal-service
  template:
    metadata:
      labels:
        app: journal-service
    spec:
      containers:
        - name: journal-service
          image: backend-journal-service:latest
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: journal-service-config
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 5
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"

