apiVersion: v1
kind: Service
metadata:
  name: journal-service
  namespace: travelmate
spec:
  selector:
    app: journal-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP

