apiVersion: v1
  SPRING_LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_BOOT_CONTEXT_CONFIG: "WARN"
  SPRING_CLOUD_CONFIG_URI: "http://config-server:8888"
  SPRING_PROFILES_ACTIVE: "docker"
data:
  namespace: travelmate
  name: journal-service-config
metadata:
kind: ConfigMap

