apiVersion: v1
kind: Secret
metadata:
  name: config-server-git-secret
  namespace: travelmate
type: Opaque
data:
  GIT_TOKEN: Z2l0aHViX3BhdF8xMUFaUEM1R1kwNFJsUTF5TGxrZGZaX2J0Z0Z4VFh4Mkhmb2ZqQlhwSHlWbXZkRnFFbXJ5UnhEYjgxVU9ybUNEWE9VQlFDREJIUERXb1JtdEha

